Repository ReactTooltip/react-tooltip, pull requests merged in 2022-10, with the labels that each got.

#796 chore: react 18 support release
  README.md
  example/.gitignore
  example/yarn.lock
Labels: semantic-release

#798 chore: add github workflows based on the pdeszynski fork
  .github/workflows/lint.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release.yaml
Labels: semantic-release

#799 chore: dependencies upgrade
  .github/workflows/release.yaml
  CHANGELOG.md
  README.md
  bower.json
  package.json
  src/index.js
  yarn.lock
Labels: Enhancement, documentation, CI/CD

#800 fix: remove github pages deploy from pipeline as we use branch instead [skip ci]
  .github/workflows/release.yaml
  example/package.json
  package.json
  yarn.lock
Labels: CI/CD

#745 feat: add borderClass prop to allow a custom border class
  README.md
  example/src/App.js
  react-tooltip.d.ts
  src/decorators/bodyMode.js
  src/index.js
  src/utils/getPosition.js
  test/index.spec.js
Labels: Enhancement

#806 feat: Refactored the arrow implementation, added custom corners support
  example/src/App.js
  example/src/index.css
  example/src/index.scss
  package.json
  src/decorators/defaultStyles.js
  src/decorators/styler.js
  src/index.js
  src/index.scss
  test/index.spec.js
Labels: Feature
