Repository ReactTooltip/react-tooltip, pull requests merged in 2022-12, with the labels that each got.

#838 Fix anchor element selector to support usage of `React.useId()`
  src/components/Tooltip/Tooltip.tsx
  src/components/TooltipController/TooltipController.tsx
Labels: Bug, Enhancement

#846 feat: dynamically setting style through styles prop
  CONTRIBUTION.md
  README.md
  docs/docs/examples/_category_.json
  docs/docs/examples/styling.mdx
  docs/docs/getting-started.mdx
  docs/docs/options.mdx
  docs/docs/upgrade-guide/_category_.json
  docs/docs/upgrade-guide/basic-examples-v4-v5.mdx
  docs/docusaurus.config.js
  docs/package.json
  docs/src/css/custom.css
  docs/static/robots.txt
  docs/yarn.lock
  package.json
  rollup.config.types.js
  src/App.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipTypes.d.ts
  src/components/Tooltip/styles.module.css
  src/components/TooltipController/TooltipController.tsx
  src/components/TooltipController/TooltipControllerTypes.d.ts
  yarn.lock
Labels: Enhancement, Feature

#849 feat: add gtm into the project and analytics configuration
  docs/docusaurus.config.js
Labels: Enhancement

#848 docs: add digital ocean to home page and project readme and update colors of docs
  README.md
  docs/src/components/HomepageSponsored/index.tsx
  docs/src/components/HomepageSponsored/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  docs/static/img/digital-ocean-powered-by.svg
Labels: Enhancement, Documentation

#845 Tooltip provider for easily sharing tooltip amongst multiple elements
  README.md
  docs/docs/examples/get-content.mdx
  docs/docs/examples/multiple-anchors.mdx
  docs/docs/examples/state.mdx
  docs/docs/options.mdx
  docs/docs/upgrade-guide/changelog-v4-v5.md
  src/App.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipTypes.d.ts
  src/components/TooltipController/TooltipController.tsx
  src/components/TooltipController/TooltipControllerTypes.d.ts
  src/components/TooltipController/constants.ts
  src/components/TooltipProvider/TooltipProvider.tsx
  src/components/TooltipProvider/TooltipProviderTypes.d.ts
  src/components/TooltipProvider/TooltipWrapper.tsx
  src/components/TooltipProvider/index.ts
  src/index-dev.tsx
  src/index.tsx
  src/test/__snapshots__/index.spec.js.snap
  src/test/index.spec.js
  src/utils/compute-positions.ts
  src/utils/debounce.ts
Labels: Enhancement, Feature
