Repository ReactTooltip/react-tooltip, pull requests merged in 2023-06, with the labels that each got.

#1038 fix: use client removed from dist files
  README.md
  docs/docs/examples/html.mdx
  docs/docs/troubleshooting.mdx
  rollup.config.prod.js
Labels: Bug, Documentation

#1047 Support more placement options in TooltipTypes.d.ts
  docs/docs/examples/place.mdx
  docs/docs/options.mdx
  src/components/Tooltip/TooltipTypes.d.ts
  src/utils/compute-positions-types.d.ts
Labels: Enhancement

#1041 feat: add manual inject styles function into the project
  .npmignore
  docs/docs/examples/anchor-select.mdx
  docs/docs/examples/render.mdx
  docs/docs/examples/styling.mdx
  docs/docs/options.mdx
  rollup-plugins/replace-before-save-file.js
  rollup.config.prod.js
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/core-styles.module.css
  src/components/Tooltip/styles.module.css
  src/index.tsx
  src/utils/handle-style.ts
Labels: Enhancement, Help Wanted
