Repository ReactTooltip/react-tooltip, pull requests merged in 2023-03, with the labels that each got.

#979 New `openOnClick` prop to toggle between old `hover` and `click` events
  docs/docs/examples/render.mdx
  docs/docs/options.mdx
  docs/docs/upgrade-guide/changelog-v4-v5.md
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipTypes.d.ts
  src/components/TooltipController/TooltipController.tsx
  src/components/TooltipController/TooltipControllerTypes.d.ts
Labels: Feature

#977 chore: make dependencies external
  esbuild.config.prod.mjs
  package.json
Labels: Enhancement

#988 fix: update node contains conditional check on Tooltip component
  src/components/Tooltip/Tooltip.tsx
Labels: Bug
