Repository ReactTooltip/react-tooltip, pull requests merged in 2023-05, with the labels that each got.

#1017 Fixed the `id` in the clickable tooltip example
  docs/docs/examples/events.mdx
Labels: Documentation

#1014 feat: change the build to auto inject css into the page
  README.md
  docs/docs/examples/anchor-select.mdx
  docs/docs/examples/basic-examples.mdx
  docs/docs/examples/children.mdx
  docs/docs/examples/content.mdx
  docs/docs/examples/delay.mdx
  docs/docs/examples/events.mdx
  docs/docs/examples/html.mdx
  docs/docs/examples/multiline.mdx
  docs/docs/examples/offset.mdx
  docs/docs/examples/place.mdx
  docs/docs/examples/provider-wrapper.mdx
  docs/docs/examples/render.mdx
  docs/docs/examples/state.mdx
  docs/docs/examples/styling.mdx
  docs/docs/examples/variant.mdx
  docs/docs/getting-started.mdx
  docs/docs/options.mdx
  docs/docs/troubleshooting.mdx
  docs/docs/upgrade-guide/basic-examples-v4-v5.mdx
  docs/package.json
  docs/yarn.lock
  rollup.config.prod.js
Labels: Enhancement

#1026 feat: log invalid CSS selector with tooltip-id
  src/components/TooltipController/TooltipController.tsx
Labels: Bug
