Repository ReactTooltip/react-tooltip, pull requests merged in 2023-02, with the labels that each got.

#930 Use same tooltip wrapper type for arrow wrapper as well
  src/components/Tooltip/Tooltip.tsx
Labels: Feature Request

#931 fix: upgrade docusaurus package to fix vulnerabilities in docs reported by github bot
  docs/package.json
  docs/yarn.lock
Labels: Dependencies

#934 Don't run jobs on draft PRs
  .github/workflows/pull-request.yaml
Labels: CI/CD

#935 fix: wrapper element changing after first render
  .npmignore
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipTypes.d.ts
  src/components/TooltipController/TooltipController.tsx
Labels: Bug

#932 fix: remove tooltip rendered element from DOM when is not showing
  docs/docs/options.mdx
  package.json
  src/components/Tooltip/Tooltip.tsx
  src/test/__snapshots__/index.spec.js.snap
  src/test/index.spec.js
  yarn.lock
Labels: Enhancement

#961 Parse `data-tooltip-float` correctly
  src/components/TooltipController/TooltipController.tsx
Labels: Bug

#962 Typo.
  docs/docs/getting-started.mdx
Labels: Documentation

#965 Add section about `ReactTooltip.rebuild()` to the docs
  README.md
  docs/docs/examples/anchor-select.mdx
  docs/docs/getting-started.mdx
  docs/docs/upgrade-guide/changelog-v4-v5.md
Labels: Documentation
