Repository ReactTooltip/react-tooltip, pull requests merged in 2023-01, with the labels that each got.

#881 fix: package main should be cjs format. (fixes #869)
  package.json
Labels: Enhancement

#901 docs: update README.md to include bundlephobia metrics
  README.md
Labels: Documentation

#926 Hide tooltip when anchor element is removed from the DOM
  src/components/Tooltip/Tooltip.tsx
Labels: Bug
